### ISSUE TITLE
Research DynamoDB

### ISSUE THREAD

**Issue by Asthajain93** [Team-5-SWE/IOT-Project#28]

**Comment by R-Yang14** [comment]
Upon more research about DynamoDB, From my findings from reddit and other websites. We might have come up with smaller scaled features to implement in our Alexa Skill. Let me paraphrase based on the sources I found.

1) https://forums.aws.amazon.com/thread.jspa?threadID=280754
        -According to someone's forum post, some user has said, "After checking metrics, I found out that DynamoDB, despite not having been actually written to or read from at all throughout the month, has been using several "capacity units" constantly, non-stop, the entire time since the creation of my tables in the database." So without even having performed read or write, the service will continue to charge for storage. We need to be careful about that. There were some more useful information to understand in the link.

2) https://blog.cloudability.com/eight-ways-to-lower-your-dynamodb-costs/
     -This site has helpful tips to limit our database usage to try to stay under free tier limitations.
From what I understand we have 25 WCU (Write Capacity Units), and 25 (Read Capacity Units).
We also have 36,000 WCUs per hr and 180,000 CONSISTENT RCUs per hr.

From what I understand we have 200million requests per month, but our free tier limit of...
25 WCU and RCU is spread out between how many tables we have. I don't have information about
how the tables eat up our free tier resources yet, but I will keep researching.
