### ISSUE TITLE
input information for events 

### ISSUE THREAD

**Issue by mpatel157** [Team-5-SWE/IOT-Project#47]

**Comment by R-Yang14** [comment]
![academic calendar](
https://user-images.githubusercontent.com/42939989/47592463-6b3c0f80-d941-11e8-9dac-2a3b9f7abe01.png
)

![ga state basketball games men women](
https://user-images.githubusercontent.com/42939989/47592464-6bd4a600-d941-11e8-8bbf-799b9dd1ee54.png
)

**Comment by R-Yang14** [comment]
![ga state basketball games](https://user-images.githubusercontent.com/42939989/47592695-60ce4580-d942-11e8-84f1-d173ee729242.png)
